In [1]:
# ways to create array using numpy

In [2]:
import numpy as np

In [3]:
# 1st way
np.array([2,4,6,7])

array([2, 4, 6, 7])

In [4]:
np.array([2,4,6,7,4.5])

array([2. , 4. , 6. , 7. , 4.5])

In [5]:
np.array([2,4,6,7,4.5,'hello'])

array(['2', '4', '6', '7', '4.5', 'hello'], dtype='<U32')

In [6]:
np.array([2,4,6,True,3.4])

array([2. , 4. , 6. , 1. , 3.4])

In [7]:
# 2nd way
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
# 3rd way
# linspace - linear space
# it generates 50 values b/w given range with equal gap/interval
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
np.linspace(1,10,num=12,retstep=True)

(array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
         5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
         9.18181818, 10.        ]),
 0.8181818181818182)

In [13]:
# 4th way
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# 5th way
np.random.random()

0.5717199806042624

In [20]:
np.random.random(5)

array([0.72010554, 0.03270561, 0.90687977, 0.48446013, 0.3938596 ])

In [21]:
np.random.random((4,4))

array([[0.17985607, 0.24093669, 0.57491632, 0.06958234],
       [0.12147767, 0.2244198 , 0.32892829, 0.06227857],
       [0.27097768, 0.33757534, 0.60733419, 0.06037306],
       [0.35866933, 0.5205743 , 0.36482644, 0.19231679]])

In [23]:
np.random.randn()

2.541443883807909

In [24]:
np.random.randn(4,4)

array([[-0.45854307, -0.64393539,  1.12442767,  0.71458475],
       [ 0.22108485,  0.45873131,  0.33670969,  2.60452683],
       [ 0.37501621,  1.33619452, -1.44794241, -1.40495411],
       [ 0.61319882,  1.7211926 , -1.47035305, -1.02789798]])

In [25]:
np.random.randint(1,100)

21

In [26]:
np.random.randint(1,100,5)

array([94, 78, 16, 34, 39])

In [27]:
np.random.randint(1,100,[5,5])

array([[72, 51, 20, 44, 65],
       [43,  8, 66, 80, 78],
       [42, 13, 81, 73, 88],
       [65, 86, 43, 24, 76],
       [55, 37, 29, 78, 72]])