In [1]:
# Indexing, Slicing and Broadcasting

In [2]:
import numpy as np

In [3]:
x = np.array([3,4,1,6,8,9,4])

In [4]:
x

array([3, 4, 1, 6, 8, 9, 4])

In [5]:
x[0]

3

In [6]:
x[4]

8

In [7]:
x[-1]

4

In [8]:
x = np.random.randint(1,100,[6,4])

In [9]:
x

array([[96, 96, 99, 49],
       [36, 23, 73, 71],
       [10, 45,  8, 45],
       [96, 92, 63,  4],
       [79, 72, 67, 40],
       [75, 77, 81, 32]])

In [10]:
x[0]

array([96, 96, 99, 49])

In [11]:
x[1]

array([36, 23, 73, 71])

In [12]:
x[-1]

array([75, 77, 81, 32])

In [13]:
x[0][0]

96

In [14]:
x[1][3]

71

In [15]:
x[0,0]

96

In [16]:
x[:]

array([[96, 96, 99, 49],
       [36, 23, 73, 71],
       [10, 45,  8, 45],
       [96, 92, 63,  4],
       [79, 72, 67, 40],
       [75, 77, 81, 32]])

In [17]:
x[0:2]

array([[96, 96, 99, 49],
       [36, 23, 73, 71]])

In [18]:
x[:,0]

array([96, 36, 10, 96, 79, 75])

In [19]:
x[:,-1]

array([49, 71, 45,  4, 40, 32])

In [20]:
x[:,2]

array([99, 73,  8, 63, 67, 81])

In [21]:
x[:,0:1]

array([[96],
       [36],
       [10],
       [96],
       [79],
       [75]])

In [22]:
x[:,2:3]

array([[99],
       [73],
       [ 8],
       [63],
       [67],
       [81]])

In [23]:
x[0:2,0:2]

array([[96, 96],
       [36, 23]])

In [24]:
x[2:4,0:2]

array([[10, 45],
       [96, 92]])

In [26]:
x[:,[0,3]]

array([[96, 49],
       [36, 71],
       [10, 45],
       [96,  4],
       [79, 40],
       [75, 32]])

In [27]:
x = np.array([3,4,6,7])

In [28]:
x

array([3, 4, 6, 7])

In [29]:
x + 5

array([ 8,  9, 11, 12])

In [30]:
x * 5

array([15, 20, 30, 35])

In [31]:
y = np.array([1,2,5,8])

In [32]:
x + y

array([ 4,  6, 11, 15])

In [33]:
x * y

array([ 3,  8, 30, 56])