In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,50,24)

In [3]:
arr

array([42, 37, 15,  8, 40, 45, 12, 10, 38, 16, 30, 19, 10,  5, 29, 19,  3,
       48, 16, 29, 11,  3, 27, 12])

In [5]:
len(dir(arr))

162

In [6]:
arr_2 = np.random.randint(1,10,24)

In [8]:
arr_2

array([9, 8, 3, 1, 8, 5, 2, 8, 5, 6, 8, 8, 6, 5, 9, 8, 5, 8, 7, 4, 5, 7,
       9, 6])

In [7]:
np.add(arr, arr_2)

array([51, 45, 18,  9, 48, 50, 14, 18, 43, 22, 38, 27, 16, 10, 38, 27,  8,
       56, 23, 33, 16, 10, 36, 18])

In [9]:
np.multiply(arr, arr_2)

array([378, 296,  45,   8, 320, 225,  24,  80, 190,  96, 240, 152,  60,
        25, 261, 152,  15, 384, 112, 116,  55,  21, 243,  72])

In [10]:
np.dot(arr, arr_2)

3570