In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,20,24)

In [3]:
np.max(x)

19

In [4]:
np.min(x)

1

In [5]:
np.mean(x)

9.791666666666666

In [6]:
x

array([13, 12,  4,  1,  6,  2, 16,  7, 14, 10,  8, 12, 15, 19, 14, 10,  4,
        6, 10, 11, 15, 11, 11,  4])

In [7]:
np.median(x)

10.5

In [8]:
np.var(x)

21.498263888888886

In [9]:
np.std(x)

4.636622034292733

In [10]:
x = np.random.randint(1,20,[6,4])

In [11]:
x

array([[ 9,  8,  9,  5],
       [ 3, 12, 13, 15],
       [12, 18, 10, 13],
       [ 6, 12, 15, 10],
       [ 1, 10,  9, 12],
       [ 8, 18,  7,  6]])

In [12]:
np.mean(x)

10.041666666666666

In [13]:
np.mean(x, axis=0)

array([ 6.5       , 13.        , 10.5       , 10.16666667])

In [14]:
np.mean(x, axis=1)

array([ 7.75, 10.75, 13.25, 10.75,  8.  ,  9.75])

In [15]:
np.median(x, axis=1)

array([ 8.5, 12.5, 12.5, 11. ,  9.5,  7.5])

In [16]:
np.median(x, axis=0)

array([ 7. , 12. ,  9.5, 11. ])